#!/usr/bin/env python3
"""Which bmcd release gained which API operation.

Why this and not `mike`
-----------------------
SQU-152 asked for "`mike` for the Reference section only". mike does not do
that: it publishes whole-site versions to gh-pages and adds a selector across
all of them, so Features and Guides would be versioned too — which the same
ticket explicitly refuses, and rightly ("versioning prose that argues is how a
site ends up with five copies of the same paragraph"). It would also
restructure a deploy that currently builds two demo panes at publish time.

The reader's actual question is narrower than a versioned site: *does the board
in front of me have this endpoint?* That is answered by one table. So this
fetches the `openapi.json` published with every bmcd release and records, for
each operation, the release it first appeared in — and names any that were
removed.

Nothing here is written by hand, and nothing is inferred: a release that
published no document is listed as such rather than guessed at.

Usage:  ./scripts/api-history.py            # every published release
        ./scripts/api-history.py --limit 12
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

REPO = "excavador-turing/bmcd"
OUT = pathlib.Path("docs/reference/api-history.md")


def releases(limit: int) -> list[str]:
    """Published, non-draft release tags, newest first."""
    raw = subprocess.run(
        ["gh", "release", "list", "--repo", REPO, "--limit", str(limit),
         "--json", "tagName,isDraft"],
        capture_output=True, text=True, check=True,
    ).stdout
    return [r["tagName"] for r in json.loads(raw) if not r["isDraft"]]


def document(tag: str) -> dict | None:
    """That release's openapi.json, or None when it published none.

    Early releases predate `bmcd --openapi`, so their absence is a fact about
    the release rather than a failure here.
    """
    proc = subprocess.run(
        ["gh", "release", "view", tag, "--repo", REPO, "--json", "assets"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return None
    names = [a["name"] for a in json.loads(proc.stdout).get("assets", [])]
    if "openapi.json" not in names:
        return None
    dl = subprocess.run(
        ["gh", "release", "download", tag, "--repo", REPO,
         "--pattern", "openapi.json", "--output", "-"],
        capture_output=True, text=True,
    )
    if dl.returncode != 0:
        return None
    try:
        return json.loads(dl.stdout)
    except json.JSONDecodeError:
        return None


def operations(doc: dict) -> set[str]:
    found = set()
    for path, item in (doc.get("paths") or {}).items():
        for method in ("get", "post", "put", "patch", "delete"):
            if method in item:
                found.add(f"{method.upper()} {path}")
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=40)
    args = ap.parse_args()

    tags = releases(args.limit)
    if not tags:
        print("no releases", file=sys.stderr)
        return 1

    # Oldest first, so "first seen" means what it says.
    seen: dict[str, dict] = {}
    per_release: list[tuple[str, set[str] | None]] = []
    for tag in reversed(tags):
        doc = document(tag)
        ops = operations(doc) if doc else None
        per_release.append((tag, ops))
        if ops is None:
            continue
        for op in ops:
            seen.setdefault(op, {"first": tag, "last": tag})
        for op in seen:
            if op in ops:
                seen[op]["last"] = tag

    described = [(t, o) for t, o in per_release if o is not None]
    newest_tag, newest_ops = described[-1]

    lines = [
        "# What each release's API had",
        "",
        "Generated by `just refresh-api-history` from the `openapi.json` that",
        "every bmcd release publishes. Not written by hand, and nothing here is",
        "inferred — a release that published no document says so.",
        "",
        "The [API reference](api/index.md) describes the **newest** release. This",
        "page answers the other question: *does the board in front of me have",
        "this operation?* Read your board's version with `tpi about`, then find",
        "it below.",
        "",
        "Every release's exact document is downloadable:",
        "",
        "```console",
        f"$ gh release download <tag> --repo {REPO} --pattern openapi.json",
        "```",
        "",
        "## Operations per release",
        "",
        "| release | operations |",
        "| --- | --- |",
    ]
    for tag, ops in reversed(per_release):
        lines.append(
            f"| `{tag}` | {len(ops)} |" if ops is not None
            else f"| `{tag}` | — no document published |"
        )

    lines += [
        "",
        "## When each operation arrived",
        "",
        "| operation | since | note |",
        "| --- | --- | --- |",
    ]
    for op in sorted(seen):
        info = seen[op]
        gone = "" if op in newest_ops else f"**removed after {info['last']}**"
        lines.append(f"| `{op}` | `{info['first']}` | {gone} |")

    lines += [
        "",
        f"As of `{newest_tag}`: **{len(newest_ops)} operations**, "
        f"{len(seen) - len(newest_ops)} since removed.",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {len(described)} releases with a document, {len(seen)} operations seen")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
