#!/usr/bin/env python3
"""Render the committed OpenAPI document as real Markdown pages.

Why this exists rather than a viewer widget
-------------------------------------------
The page this replaces was one 106,000-pixel scroll: 33 operations, 176
generated headings, 74 tables, and a table of contents with three entries.
Every operation had an anchor and none was reachable, because the previous
renderer emits HTML *after* MkDocs has built the table of contents, so its
headings never enter it.

Swapping in a prettier viewer (Scalar, Elements, Redoc) fixes navigation and
loses something worth more: those render one JavaScript widget, which the
site's search cannot index. On a reference site, search is how people find
things. That trade was refused once already, deliberately, and this keeps
refusing it -- Markdown headings are indexed, linkable and navigable at the
same time.

The document is still generated by the daemon and committed at a pinned
version. This script only changes the shape it is read in, never its content:
nothing here invents a field, and an operation absent from the document is
absent from the site.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
from collections import OrderedDict

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "docs" / "reference" / "openapi.json"
OUTDIR = ROOT / "docs" / "reference" / "api"

# The document carries no tags -- every operation is untagged -- so grouping
# comes from the path, which is the next most honest thing available. If the
# daemon ever grows tags, prefer them and delete this table.
GROUPS: "OrderedDict[str, tuple[str, tuple[str, ...]]]" = OrderedDict(
    board=("The board", ("about", "info", "health", "hostname", "config", "reboot", "reload")),
    nodes=("The nodes", ("nodes", "power", "reset", "usb", "usb-boot", "node-to-msd")),
    firmware=("Firmware", ("firmware",)),
    storage=("Storage", ("sdcard",)),
    network=("Network and time", ("network", "ntp")),
    thermal=("Cooling and thermals", ("cooling", "thermal")),
)

METHODS = ("get", "post", "put", "patch", "delete")


def resource_of(path: str) -> str:
    """First segment after /api/bmc/ -- the resource an operation acts on."""
    tail = path.removeprefix("/api/bmc").strip("/")
    return tail.split("/")[0] if tail else "(root)"


def group_of(path: str) -> str:
    res = resource_of(path)
    for key, (_title, members) in GROUPS.items():
        if res in members:
            return key
    return "board"


def deref(spec: dict, node):
    """Resolve one $ref. Not recursive by design: schemas here are shallow,
    and a recursive resolver on a self-referential schema hangs silently."""
    if isinstance(node, dict) and "$ref" in node:
        ref = node["$ref"]
        if ref.startswith("#/components/schemas/"):
            name = ref.rsplit("/", 1)[-1]
            return name, spec.get("components", {}).get("schemas", {}).get(name, {})
    return None, node


def type_of(schema: dict) -> str:
    """A short human type for a table cell."""
    if not schema:
        return "—"
    if "$ref" in schema:
        return f"`{schema['$ref'].rsplit('/', 1)[-1]}`"
    t = schema.get("type")
    if t == "array":
        inner = schema.get("items", {})
        return f"array of {type_of(inner)}"
    if isinstance(t, list):
        return " or ".join(f"`{x}`" for x in t)
    if t:
        fmt = schema.get("format")
        return f"`{t}`" + (f" ({fmt})" if fmt else "")
    if "enum" in schema:
        return " or ".join(f"`{e}`" for e in schema["enum"])
    return "`object`"


def clean(text: str | None) -> str:
    """One-line a description for a table cell without mangling code spans."""
    if not text:
        return ""
    return re.sub(r"\s*\n\s*", " ", text).replace("|", r"\|").strip()


def properties_table(schema: dict) -> list[str]:
    props = schema.get("properties") or {}
    if not props:
        return []
    required = set(schema.get("required") or [])
    out = ["", "| field | type | required | description |", "|---|---|---|---|"]
    for name, sub in props.items():
        out.append(
            f"| `{name}` | {type_of(sub)} | {'yes' if name in required else 'no'} "
            f"| {clean(sub.get('description'))} |"
        )
    out.append("")
    return out


def schema_block(spec: dict, schema: dict, label: str) -> list[str]:
    """A named schema rendered as a collapsed block.

    Collapsed because 74 permanently-expanded tables are what made the old
    page unreadable. The detail is still on the page and still indexed --
    `pymdownx.details` renders real HTML, it does not lazy-load.
    """
    # Most responses here are `array of <ref>`; resolving the array itself
    # finds no properties and silently renders nothing, which is how the
    # commonest shape on this API would have lost its schema entirely.
    # Unwrap to the item first.
    note = ""
    if schema.get("type") == "array" and "items" in schema:
        schema = schema["items"]
        note = " (each element)"
    name, resolved = deref(spec, schema)
    title = f"{label}{note}: `{name}`" if name else f"{label}{note}"
    rows = properties_table(resolved)
    if not rows:
        return []
    return [f'??? note "{title}"'] + [("    " + r if r else "") for r in rows]


def render_operation(spec: dict, path: str, method: str, op: dict) -> list[str]:
    out: list[str] = []
    # The heading text is the anchor. Keeping "METHOD /path" preserves the
    # anchors the previous renderer produced, so existing deep links keep
    # working -- on a different page, which is why index.md lists them all.
    out.append(f"## {method.upper()} {path}")
    out.append("")
    if op.get("summary"):
        out.append(f"**{op['summary']}**")
        out.append("")
    if op.get("description"):
        out.append(op["description"])
        out.append("")

    params = op.get("parameters") or []
    if params:
        out += ["| parameter | in | required | description |", "|---|---|---|---|"]
        for p in params:
            out.append(
                f"| `{p.get('name')}` | {p.get('in')} | "
                f"{'yes' if p.get('required') else 'no'} | {clean(p.get('description'))} |"
            )
        out.append("")

    body = op.get("requestBody")
    if body:
        for ctype, media in (body.get("content") or {}).items():
            out += schema_block(spec, media.get("schema") or {}, f"Request body (`{ctype}`)")
        out.append("")

    responses = op.get("responses") or {}
    if responses:
        out += ["| response | body | meaning |", "|---|---|---|"]
        for code, r in responses.items():
            content = r.get("content") or {}
            if content:
                ctype, media = next(iter(content.items()))
                body_desc = f"`{ctype}` — {type_of(media.get('schema') or {})}"
            else:
                body_desc = "empty"
            out.append(f"| `{code}` | {body_desc} | {clean(r.get('description'))} |")
        out.append("")
        for code, r in responses.items():
            for ctype, media in (r.get("content") or {}).items():
                out += schema_block(spec, media.get("schema") or {}, f"`{code}` body (`{ctype}`)")
        out.append("")
    return out


def main() -> int:
    if not SPEC.exists():
        print(f"missing {SPEC}", file=sys.stderr)
        return 1
    spec = json.loads(SPEC.read_text())
    version = spec.get("info", {}).get("version", "unknown")

    buckets: dict[str, list[tuple[str, str, dict]]] = {k: [] for k in GROUPS}
    for path in sorted(spec.get("paths", {})):
        for method, op in spec["paths"][path].items():
            if method in METHODS:
                buckets[group_of(path)].append((path, method, op))

    OUTDIR.mkdir(parents=True, exist_ok=True)
    written: list[pathlib.Path] = []
    total = 0

    for key, (title, _members) in GROUPS.items():
        ops = buckets[key]
        if not ops:
            continue
        total += len(ops)
        lines = [
            f"# {title}",
            "",
            f"Generated from the committed OpenAPI document, **bmcd {version}**. "
            "Do not edit this file: `just refresh-api` rewrites it.",
            "",
        ]
        for path, method, op in ops:
            lines += render_operation(spec, path, method, op)
        page = OUTDIR / f"{key}.md"
        page.write_text("\n".join(lines).rstrip() + "\n")
        written.append(page)
        print(f"  {page.relative_to(ROOT)}: {len(ops)} operations")

    # The index is the "findable in one action" surface, and the landing spot
    # for anyone following an old deep link into the single-page version.
    idx = [
        "# Every operation",
        "",
        f"Generated from the committed OpenAPI document, **bmcd {version}**. "
        "Do not edit this file: `just refresh-api` rewrites it.",
        "",
        "One row per operation. The prose about what this API *is* — the two "
        "spellings, what the document describes, authentication — is on "
        "[The API](../api.md).",
        "",
        "| operation | method | path | group |",
        "|---|---|---|---|",
    ]
    for key, (title, _m) in GROUPS.items():
        for path, method, op in buckets[key]:
            # Match MkDocs' own slug for the heading "METHOD /path": lowercase,
            # spaces become hyphens, everything else is dropped. Guessing this
            # produced 33 links that resolved to nothing while the build still
            # passed --strict, because a missing anchor is only an INFO.
            anchor = re.sub(r"[^a-z0-9-]+", "", f"{method} {path}".lower().replace(" ", "-"))
            summary = clean(op.get("summary")) or op.get("operationId", "")
            idx.append(f"| {summary} | `{method.upper()}` | [`{path}`]({key}.md#{anchor}) | {title} |")
    idx.append("")
    (OUTDIR / "index.md").write_text("\n".join(idx) + "\n")
    written.append(OUTDIR / "index.md")

    print(f"  {len(written)} pages, {total} operations, from bmcd {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
