#!/usr/bin/env python3
"""One file that tells a machine what this site holds, and in what order.

An assistant asked about this firmware does not read a nav. It fetches a page
or two and answers from them, and which two it picks decides whether the
answer is right. `llms.txt` is the convention for saying so: a title, one
paragraph, then the links that matter with one line each about what is in
them.

It is generated, for the reason everything else here is generated -- a
hand-kept index of 91 pages is an index that is wrong by the third release.
The nav supplies the order (it is already the order a person is meant to read
in), each page supplies its own one-line description, and
`scripts/description-lint.py` guarantees every page has one.

`llms-full.txt` -- the whole site as one document -- is deliberately NOT
written. These pages are macros and snippets; the markdown on disk is not the
page a reader gets, and pouring built HTML back into markdown would publish a
third version of the text that nobody checks. If an index asks for it, build
it from the built pages, not from the source.

    just llms            # write docs/llms.txt
    just llms --check    # fail if the committed file is stale
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "llms.txt"
ORG = "excavador-turing"

# The one paragraph. It says what the thing IS and why it exists, because
# that is the question every other page assumes has been answered.
BLURB = (
    "A maintained fork of the Turing Pi 2 BMC firmware — the management "
    "computer on a Turing Pi 2 cluster board, which powers, flashes and "
    "consoles the four compute modules. Upstream's last release is v2.1.0 "
    "(February 2025) and its update mirror stops earlier still. This fork "
    "adds an update that takes itself back when the board does not come "
    "up right, VLANs on the board's own switch, a certificate a browser "
    "accepts, the board's own address from the interface, and metrics "
    "where there were none. Everything on this site was measured on real "
    "boards; every page says where and when."
)

# Not everything in the nav is a page an assistant should read. The demo is
# an application shell whose text is one board's captured data.
SKIP = {"demo/index.md"}


def site_url() -> str:
    for line in (ROOT / "mkdocs.yml").read_text().splitlines():
        if line.startswith("site_url:"):
            return line.split(":", 1)[1].strip().strip('"\'').rstrip("/")
    return ""


def nav() -> list:
    cfg = yaml.safe_load((ROOT / "mkdocs.yml").read_text())
    return cfg.get("nav") or []


def front_matter(src: str) -> dict:
    p = DOCS / src
    if not p.exists():
        return {}
    text = p.read_text()
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return {}


def url_of(src: str, base: str) -> str:
    """The published URL of a source path, as mkdocs' directory URLs make it."""
    s = src[:-3] if src.endswith(".md") else src
    if s.endswith("/index"):
        s = s[:-6]
    elif s == "index":
        s = ""
    return f"{base}/{s}/" if s else f"{base}/"


def walk(node, out: list[tuple[str, str, str]], group: str = "") -> None:
    """Flatten a nav subtree into (group, title, src), keeping its order.

    `group` is the nearest sub-heading inside the section -- "The arguments",
    "Reference", "Changelogs". Eleven feature pages and eleven argument pages
    share their titles, so without it the list reads as the same page twice.
    """
    if isinstance(node, str):
        out.append((group, "", node))
    elif isinstance(node, dict):
        for title, child in node.items():
            if isinstance(child, str):
                out.append((group, title, child))
            else:
                walk(child, out, title)
    elif isinstance(node, list):
        for child in node:
            walk(child, out, group)


def recent_posts(base: str, limit: int = 10) -> list[str]:
    posts = []
    for p in (DOCS / "news" / "posts").glob("*.md"):
        fm = front_matter(str(p.relative_to(DOCS)))
        if fm.get("date") and fm.get("slug"):
            posts.append((str(fm["date"]), fm["slug"], fm.get("title", ""),
                          fm.get("description", "")))
    posts.sort(reverse=True)
    return [f"- [{t}]({base}/news/{slug}/): {d}"
            for _when, slug, t, d in posts[:limit]]


def render() -> str:
    base = site_url()
    lines = [
        "# Turing Pi 2 BMC firmware (excavador-turing fork)",
        "",
        f"> {BLURB}",
        "",
        "Generated by `scripts/llms.py` from the site's own navigation and "
        "each page's description. Do not edit.",
        "",
    ]
    counted = 0
    for section in nav():
        if not isinstance(section, dict):
            continue
        (heading, child), = section.items()
        pairs: list[tuple[str, str, str]] = []
        walk(child if not isinstance(child, str) else {heading: child}, pairs)
        rows, seen_urls = [], set()
        for group, title, src in pairs:
            if src in SKIP or not src.endswith(".md"):
                continue
            fm = front_matter(src)
            if (fm.get("robots") or "").startswith("noindex"):
                continue
            url = url_of(src, base)
            # Two sources can claim one URL (a page and a directory index of
            # the same name). The nav shows both; an index must not.
            if url in seen_urls:
                continue
            seen_urls.add(url)
            desc = (fm.get("description") or "").strip()
            name = title or fm.get("title") or src
            if group and group != heading:
                name = f"{group}: {name}"
            rows.append(f"- [{name}]({url}): {desc}")
            counted += 1
        if heading == "News":
            rows += recent_posts(base)
            counted += len(rows) - 1
        if rows:
            lines += [f"## {heading}", ""] + rows + [""]

    lines += [
        "## Optional",
        "",
        "Sources this site is generated from, when the page is not enough.",
        "",
        f"- [Firmware CHANGELOG.md](https://raw.githubusercontent.com/{ORG}/"
        "BMC-Firmware/hive/CHANGELOG.md): every release of the image, with "
        "what it pins.",
        f"- [bmcd CHANGELOG.md](https://raw.githubusercontent.com/{ORG}/"
        "bmcd/hive/CHANGELOG.md): the daemon that serves the API.",
        f"- [BMC-UI CHANGELOG.md](https://raw.githubusercontent.com/{ORG}/"
        "BMC-UI/hive/CHANGELOG.md): the web interface and the fleet page.",
        f"- [tpi CHANGELOG.md](https://raw.githubusercontent.com/{ORG}/"
        "tpi/hive/CHANGELOG.md): the command line.",
        f"- [openapi.json]({base}/reference/openapi.json): the API as the "
        "board itself describes it.",
        f"- [feed.xml]({base}/feed.xml): new releases, as an Atom feed.",
        "",
    ]
    if counted < 20:
        sys.exit(f"llms: only {counted} pages found in the nav — refusing to "
                 f"write an index that thin")
    print(f"  {counted} entries from the nav")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what this writes")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print("llms: docs/llms.txt is stale — run `just llms`",
                  file=sys.stderr)
            return 1
        print("  docs/llms.txt matches the nav")
        return 0
    OUT.write_text(text)
    print(f"  -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
